blueprint:
  name: Gestion Climatisation Automatique
  description: Gère la climatisation avec des actions définies automatiquement selon la saison détectée.
  domain: automation
  input:
    plage_horaire:
      name: Plage Horaire
      description: Jour ou Nuit.
      selector:
        select:
          options:
            - "jour"
            - "nuit"
    plage_semaine:
      name: Plage Semaine
      description: Permet de sélectionner si l'automatisation s'applique à la semaine ou au week-end.
      selector:
        select:
          options:
            - "semaine"
            - "week-end"
    thermometres_intérieur:
      name: Capteur de température (Intérieur)
      description: Capteur utilisé pour mesurer la température intérieure.
      selector:
        entity:
          domain: sensor
    thermometres_exterieur:
      name: Capteur de température (Extérieur)
      description: Capteur utilisé pour mesurer la température extérieure.
      selector:
        entity:
          domain: sensor
    climatiseurs:
      name: Climatiseur
      description: Entité du climatiseur à contrôler.
      selector:
        entity:
          domain: climate
    mode_printemps:
      name: Mode Printemps
      description: Mode à utiliser pendant le printemps.
      selector:
        select:
          options:
            - "off"
            - "auto"
            - "cool"
            - "heat"
            - "dry"
            - "fan_only"
    mode_ete:
      name: Mode Été
      description: Mode à utiliser pendant l'été.
      selector:
        select:
          options:
            - "off"
            - "auto"
            - "cool"
            - "heat"
            - "dry"
            - "fan_only"
    mode_automne:
      name: Mode Automne
      description: Mode à utiliser pendant l'automne.
      selector:
        select:
          options:
            - "off"
            - "auto"
            - "cool"
            - "heat"
            - "dry"
            - "fan_only"
    mode_hiver:
      name: Mode Hiver
      description: Mode à utiliser pendant l'hiver.
      selector:
        select:
          options:
            - "off"
            - "auto"
            - "cool"
            - "heat"
            - "dry"
            - "fan_only"
    temperature_printemps:
      name: Température cible (Printemps)
      description: Température à maintenir pendant le printemps.
      selector:
        number:
          min: 18
          max: 26
          step: 0.5
    temperature_ete:
      name: Température cible (Été)
      description: Température à maintenir pendant l'été.
      selector:
        number:
          min: 18
          max: 26
          step: 0.5
    temperature_automne:
      name: Température cible (Automne)
      description: Température à maintenir pendant l'automne.
      selector:
        number:
          min: 18
          max: 26
          step: 0.5
    temperature_hiver:
      name: Température cible (Hiver)
      description: Température à maintenir pendant l'hiver.
      selector:
        number:
          min: 18
          max: 26
          step: 0.5
    seuil_tolerance:
      name: Seuil de tolérance
      description: Ajustement à appliquer autour de la température cible pour déclencher la climatisation.
      selector:
        number:
          min: 0
          max: 3
          step: 0.5
