blueprint:
  name: "Gestion Climatisation - Hiver"
  description: "Gestion de climatisation pour l'hiver avec températures jour/nuit"
  domain: automation
  input:
    climate_entity:
      name: "Climatiseur"
      selector:
        entity:
          domain: climate
    
    temp_sensor:
      name: "Capteur température"
      selector:
        entity:
          domain: sensor
          device_class: temperature
    
    # Configuration horaires
    day_start:
      name: "Début de journée"
      selector:
        time: {}
      default: "07:00:00"
    
    day_end:
      name: "Fin de journée"
      selector:
        time: {}
      default: "22:00:00"
    
    # Configuration Hiver
    winter_day_temp:
      name: "Température jour"
      selector:
        number:
          min: 18
          max: 24
          step: 0.5
          unit_of_measurement: °C
      default: 19

    winter_night_temp:
      name: "Température nuit"
      selector:
        number:
          min: 16
          max: 22
          step: 0.5
          unit_of_measurement: °C
      default: 17
    
    winter_mode:
      name: "Mode climatisation"
      selector:
        select:
          options:
            - auto
            - cool
            - heat
      default: heat
    
    max_temp:
      name: "Température maximale"
      selector:
        number:
          min: 20
          max: 30
          step: 0.5
          unit_of_measurement: °C
      default: 24

trigger:
  - platform: state
    entity_id: !input "temp_sensor"
  - platform: time_pattern
    minutes: "/5"

variables:
  is_daytime: >
    {% set current_time = now().strftime("%H:%M:%S") %}
    {% set day_start = states('input_datetime.day_start') %}
    {% set day_end = states('input_datetime.day_end') %}
    {{ current_time >= day_start and current_time <= day_end }}

  target_temp: >
    {% if is_daytime %}
      {{ states(winter_day_temp) }}
    {% else %}
      {{ states(winter_night_temp) }}
    {% endif %}

condition:
  - condition: template
    value_template: "{{ states(temp_sensor)|float > target_temp|float }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ states(temp_sensor)|float > states(max_temp)|float }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input "climate_entity"
            data:
              hvac_mode: cool
          - service: climate.set_temperature
            target:
              entity_id: !input "climate_entity"
            data:
              temperature: "{{ states(max_temp)|float }}"
    
    default:
      - service: climate.set_hvac_mode
        target:
          entity_id: !input "climate_entity"
        data:
          hvac_mode: "{{ states(winter_mode) }}"
      - service: climate.set_temperature
        target:
          entity_id: !input "climate_entity"
        data:
          temperature: "{{ target_temp|float }}"

  - service: logbook.log
    data:
      name: "Climatisation Hiver"
      message: "Mode: {{ states(winter_mode) }}, Période: {{ 'Jour' if is_daytime else 'Nuit' }}, Température cible: {{ target_temp }}°C"